@startuml
title Shannon's Gas Tracker
left to right direction

actor "Dr. Umphress" as User
rectangle {

    usecase (Record Gas Fillup) as RGF
    usecase (Record Maintenance) as RM
    usecase (Record Miscellaneous) as RMI

    usecase (View Service Record) as VSR

  usecase (Delete Entry) as DE


    User - VSR

    User - DE

    User - RGF
    User - RM
    User - RMI


}
@enduml